### ISSUE TITLE
core apiGroup should be imported directly from "" empty group

### ISSUE THREAD

**Issue by shinebayar-g** [konfjs/k8skonf#103]
So instead of this

```ts
import { Namespace } from '@k8skonf/core/core/v1';
```

it can be shortened to this.

```ts
import { Namespace } from '@k8skonf/core/v1';
```

Because [kubernetes yaml format](https://kubernetes.io/docs/tasks/administer-cluster/namespaces-walkthrough/) looks like this

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
```
